version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  build:
    executor:
      name: 'samvera/ruby'
      ruby_version: "2.5.7"

    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: "2.5.7"
          project: linkeddata
      - samvera/parallel_rspec
